### ISSUE TITLE
runBlockingTest does not really block

### ISSUE THREAD

**Issue by speekha** [googlecodelabs/kotlin-coroutines#35]
In kotlin-coroutines-end, comments of the refreshTitle_MockitoVersion() test recommends to use runBlockingTest to launch the coroutine and wait for its completion.
Since the runBlockingTest block and the viewModel do not share the same coroutine scope (TestCoroutineScope on one hand vs viewModelScope in the other) or the same Job, the runBlockingTest does not wait for completion when the refreshTitle switches execution to Dispatchers.IO (setting a break point or a delay inside the TitleRepository.refreshTitle method shows that the tests completes without waiting for a response).
Shouldn't the runBlockingTest's scope and the viewModelScope share a Job to be able to wait for each other?

**Comment by objcode** [comment]
Since it will inject dispatchers Main which viewModelScope, they'll share the test dispatcher. They don't need to share a job in order to control execution order due to TestCoroutineDispatcher.

The completion checking isn't quite as strict as if they shared a scope, but it is sufficient for most use cases (such as this one). It will unfortunately not catch suspended coroutines started by calling launch in viewModelScope when coded this way.
